---
version: '3'
services:
  node1:
    build:
      context: .
    ports:
    - "3001:3001"
  node2:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - "3002:3001"
    environment:
      - PEERS=ws://node1:6001
  node3:
    environment:
      - PEERS=ws://node2:6001
    build:
      context: ./
    ports:
    - "3003:3001"
